import type { Metadata } from "next";
import { site, social } from "@/content/site";
import { alternates, htmlLang, locales, localePath, ogLocale, type Locale } from "@/i18n/config";

/** 1200×630 share images, generated by `npm run og-images`. */
export const defaultOgImage = { url: "/images/og/default.jpg", width: 1200, height: 630 };
export const projectOgImage = (slug: string) => ({ url: `/images/og/${slug}.jpg`, width: 1200, height: 630 });

type PageMeta = {
  locale: Locale;
  /** Portuguese path, e.g. "/cases". */
  path: string;
  /** Page title; " — Webcraftz" is appended unless `brandTitle` is false (home). */
  title: string;
  brandTitle?: boolean;
  description: string;
  image?: { url: string; width: number; height: number; alt?: string };
  type?: "website" | "article";
};

/**
 * Metadata for one page in one language: canonical + hreflang, and Open Graph / Twitter
 * tags that describe this page (Next replaces, not merges, a parent's `openGraph`).
 */
export function pageMetadata({
  locale,
  path,
  title,
  brandTitle = true,
  description,
  image = defaultOgImage,
  type = "website",
}: PageMeta): Metadata {
  const fullTitle = brandTitle ? `${title} — ${site.name}` : title;
  const images = [{ ...image, alt: image.alt ?? fullTitle }];
  return {
    title: brandTitle ? title : { absolute: title },
    description,
    alternates: alternates(locale, path),
    openGraph: {
      title: fullTitle,
      description,
      url: localePath(locale, path),
      siteName: site.name,
      locale: ogLocale[locale],
      alternateLocale: locales.filter((l) => l !== locale).map((l) => ogLocale[l]),
      type,
      images,
    },
    twitter: { card: "summary_large_image", title: fullTitle, description, images },
  };
}

/** Absolute URL for a Portuguese path in a language. */
export const absoluteUrl = (locale: Locale, path: string) => new URL(localePath(locale, path), site.url).href;

/** schema.org data for the business and the site, rendered on the home page. */
export function organizationJsonLd(locale: Locale, description: string) {
  const url = absoluteUrl(locale, "/");
  return [
    {
      "@context": "https://schema.org",
      "@type": "ProfessionalService",
      "@id": `${site.url}/#organization`,
      name: site.name,
      url: site.url,
      email: site.email,
      description,
      image: new URL(defaultOgImage.url, site.url).href,
      areaServed: "Worldwide",
      address: { "@type": "PostalAddress", addressRegion: "RS", addressCountry: "BR" },
      sameAs: social.filter((s) => !("needsReview" in s && s.needsReview)).map((s) => s.href),
    },
    {
      "@context": "https://schema.org",
      "@type": "WebSite",
      "@id": `${url}#website`,
      name: site.name,
      url,
      inLanguage: htmlLang[locale],
      publisher: { "@id": `${site.url}/#organization` },
    },
  ];
}

/** Breadcrumb trail (Home › Cases › Project) as schema.org data. */
export function breadcrumbJsonLd(locale: Locale, items: { name: string; path: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: item.name,
      item: absoluteUrl(locale, item.path),
    })),
  };
}
